### ISSUE TITLE
[Bug] Intense battery drain when using nonroot without Play Services

### ISSUE THREAD

**Issue by liamwhite** [TeamVanced/Vanced#1220]
**Bug description**
CPU usage spikes to 100% of a single big core and logcat is filled with the following messages (thousands per second):
```
08-26 11:11:23.478  4183  4183 W YT.MDX.acov: CastAppId for type 0 not found. Defaulting to mainCastAppId.
08-26 11:11:23.478  4183  4230 W DynamiteLoaderImpl: Failed to retrieve remote feature version.
08-26 11:11:23.478  4183  4230 W DynamiteModule: Local module descriptor class for com.google.android.gms.cast.framework.dynamite not found.
08-26 11:11:23.479  4183  4230 W DynamiteModule: IDynamite loader version = 2, no high precision latency measurement.
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: Error fetching CastContext.
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: qeu: qud: No acceptable module found. Local version is 0 and remote version is 0.
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at qfk.c(PG:8)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at qdw.<init>(PG:12)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at qdv.call(PG:3)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at rog.run(PG:1)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at amrx.run(PG:4)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at sfp.run(PG:5)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at sfb.run(PG:2)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at ser.run(PG:2)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at java.lang.Thread.run(Thread.java:923)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: Caused by: qud: No acceptable module found. Local version is 0 and remote version is 0.
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at quh.e(PG:128)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at qfk.c(PG:2)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	... 10 more
08-26 11:11:23.479  4183  4183 W YT.MDX.acov: CastAppId for type 0 not found. Defaulting to mainCastAppId.
08-26 11:11:23.479  4183  4230 W DynamiteLoaderImpl: Failed to retrieve remote feature version.
08-26 11:11:23.479  4183  4230 W DynamiteModule: Local module descriptor class for com.google.android.gms.cast.framework.dynamite not found.
08-26 11:11:23.479  4183  4230 W DynamiteModule: IDynamite loader version = 2, no high precision latency measurement.
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: Error fetching CastContext.
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: qeu: qud: No acceptable module found. Local version is 0 and remote version is 0.
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at qfk.c(PG:8)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at qdw.<init>(PG:12)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at qdv.call(PG:3)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at rog.run(PG:1)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at amrx.run(PG:4)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at sfp.run(PG:5)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at sfb.run(PG:2)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at ser.run(PG:2)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at java.lang.Thread.run(Thread.java:923)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: Caused by: qud: No acceptable module found. Local version is 0 and remote version is 0.
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at quh.e(PG:128)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	at qfk.c(PG:2)
08-26 11:11:23.479  4183  4183 E YT.MDX.CastSdkClient: 	... 10 more
08-26 11:11:23.479  4183  4183 W YT.MDX.acov: CastAppId for type 0 not found. Defaulting to mainCastAppId.
08-26 11:11:23.479  4183  4230 W DynamiteLoaderImpl: Failed to retrieve remote feature version.
```
This causes the device to get physically hot to the touch and drains the battery rapidly.

**Variant**
Non-Root

**Vanced version**
Occurs on any version after 15.43.32. No issues in 15.43.32.

**Android version**
Android 11 

**Device**
Physical Pixel 4a running LineageOS, also Pixel 4a x86_64 profile in Android Emulator

**Steps to Reproduce**
Steps to reproduce the error:
1. Install Android 11/Pixel 4a in AVD Manager
2. Enter `adb shell`
3. Disable Play Services apps:
   ```
   generic_x86:/ $ pm list packages | grep google
   package:com.google.android.overlay.googlewebview
   package:com.google.android.apps.maps
   package:com.google.android.webview
   package:com.google.android.gms
   package:com.google.android.gsf
   package:com.google.android.overlay.emulatorgmsconfig
   package:com.google.android.sdksetup
   generic_x86:/ $ su
   generic_x86:/ # pm disable com.google.android.gsf
   Package com.google.android.gsf new state: disabled
   generic_x86:/ # pm disable com.google.android.gms
   Package com.google.android.gms new state: disabled
   255|generic_x86:/ # pm disable com.google.android.overlay.emulatorgmsconfig
   Package com.google.android.overlay.emulatorgmsconfig new state: disabled
   generic_x86:/ # pm disable com.google.android.sdksetup
   Package com.google.android.sdksetup new state: disabled
   generic_x86:/ # pm disable com.google.android.overlay.googlewebview
   Package com.google.android.overlay.googlewebview new state: disabled
   generic_x86:/ # pm disable com.google.android.apps.maps
   Package com.google.android.apps.maps new state: disabled
   ```
4. Install Vanced Manager and Vanced (I used dark theme, but I doubt this matters)
5. Open Vanced, notice huge CPU usage spike
6. Read from logcat fails because the application is generating so much log output that the ring expires before `logcat` can even read it from binder:
   ```
   generic_x86:/ $ logcat
   logcat: Unexpected EOF!
   
   This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
   messages as quickly as they were being produced.
   
   If you have enabled significant logging, look into using the -G option to increase log buffer sizes.
   1|generic_x86:/ $ logcat -G 10M
   generic_x86:/ $ logcat
   ```
7. See above messages repeatedly

**Expected behavior**
App should not write thousands of log lines per second to logcat and should not consume a whole CPU core crashing after attempting to perform a nonexistent RPC

**Comment by Jastreb** [comment]
Possibly related https://github.com/YTVanced/VancedMicroG/issues/162

**Comment by Srdjan667** [comment]
> Possibly related [YTVanced/VancedMicroG#162](https://github.com/YTVanced/VancedMicroG/issues/162)

I think bug is related to YT vanced, bc I uninstalled microG overnight and drain continued.

**Comment by liamwhite** [comment]
I can confirm that the issue here still occurs with latest Vanced + Manager.

**Comment by KevinX8** [comment]
> I can confirm that the issue here still occurs with latest Vanced + Manager.

See my first reply, there is no fix because microg has still not added the service, your only options are install Google play services or try the root version of vanced (considering you have a custom ROM anyways)

**Comment by liamwhite** [comment]
Is it not possible to patch this at the smali level by catching the exception and sleeping after a failure?

**Comment by KevinX8** [comment]
> Is it not possible to patch this at the smali level by catching the exception and sleeping after a failure?

If you know how to do that then by all means do it and send a patch for it on the vanced discord or here

**Comment by liamwhite** [comment]
```diff
diff --git a/smali_classes4/quh.smali b/smali_classes4/quh.smali
index f947ad1b..6cd2baaa 100644
--- a/smali_classes4/quh.smali
+++ b/smali_classes4/quh.smali
@@ -2280,40 +2280,44 @@
 
     invoke-virtual {v4, v2}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
 
     const-string v2, " and remote version is "
 
     invoke-virtual {v4, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
 
     invoke-virtual {v4, v3}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;
 
     const-string v2, "."
 
     invoke-virtual {v4, v2}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;
 
     invoke-virtual {v4}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;
 
     move-result-object v2
 
     .line 128
     invoke-direct {v1, v2}, Lqud;-><init>(Ljava/lang/String;)V
 
+    const-wide v2, 0xea60
+
+    invoke-static {v2, v3}, Ljava/lang/Thread;->sleep(J)V
+
     .line 127
     throw v1
     :try_end_12
     .catchall {:try_start_12 .. :try_end_12} :catchall_4
 
     :catchall_4
     move-exception v0
 
     move-object v1, v0
 
     const-wide/16 v2, 0x0
 
     cmp-long v4, v9, v2
 
     if-nez v4, :cond_23
 
     .line 59
     sget-object v2, Lquh;->j:Ljava/lang/ThreadLocal;
 
     .line 122
```

solves the issue for me, the exception is then only thrown once a minute
```
12-10 18:49:24.367  1534  1534 E YT.MDX.CastSdkClient: Error fetching CastContext.
12-10 18:49:24.367  1534  1534 E YT.MDX.CastSdkClient: qeu: qud: No acceptable module found. Local version is 0 and remote version is 0.
12-10 18:49:24.367  1534  1534 E YT.MDX.CastSdkClient: 	...
12-10 18:50:24.368  1534  1534 E YT.MDX.CastSdkClient: Error fetching CastContext.
12-10 18:50:24.368  1534  1534 E YT.MDX.CastSdkClient: qeu: qud: No acceptable module found. Local version is 0 and remote version is 0.
12-10 18:50:24.368  1534  1534 E YT.MDX.CastSdkClient: 	...
12-10 18:51:24.369  1534  1534 E YT.MDX.CastSdkClient: Error fetching CastContext.
12-10 18:51:24.369  1534  1534 E YT.MDX.CastSdkClient: qeu: qud: No acceptable module found. Local version is 0 and remote version is 0.
12-10 18:51:24.369  1534  1534 E YT.MDX.CastSdkClient: 	...
```

**Comment by liamwhite** [comment]
Patch is attached to issue, waiting for further feedback.
